### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Felleus** [Kqliber/Expansion-RNG#4]
Please add the ability to generate different numbers in different cells, for example in the GUI menu. Here's an example: PlaceHolder can look something like %rng_name_number, number%, where name will be a limiter for PlaceHolder so that it doesn't generate the same values in different GUI cells. I hope you understand me, thank you!!

**Comment by Kqliber** [comment]
i think due to the way placeholders are handled, this is impossible, sorry.
