### ISSUE TITLE
Suggestion: weighted numbers

### ISSUE THREAD

**Issue by datatags** [Kqliber/Expansion-RNG#7]
It'd be cool if you could specify weights for the returned numbers, for example `%rng_0|75,1|25%` would have a 25% chance of returning 1 but a 75% chance of returning 0. Or even just being able to put in a list of numbers to pick from to return, like `%rng_0|0|0|1%` has 3 chances to return a 0 and one chance to return a 1.

Thanks!

**Comment by Kqliber** [comment]
I like the sound of this and will have a look at trying to implement this when I have some spare time. Thanks for the suggestion!

**Comment by Kqliber** [comment]
Released version [1.4.0](https://api.extendedclip.com/expansions/rng/versions/rng-140/) to the ecloud, adding lists and weighted numbers.
Let me know if u run into any issues!

**Comment by datatags** [comment]
Awesome, thanks!
