### ISSUE TITLE
Placeholder in placeholder

### ISSUE THREAD

**Issue by F1reP0wer12345** [Kqliber/Expansion-RNG#8]
Hello,
I created a placeholder that is supposed to get a random number between two placeholders using math, which in itself also has a placeholder. This didn't work. The same problem appeared on another papi expansion, and was fixed. I will put a link below to that same issue to give you a better understanding of what i mean.
[github issue link](https://github.com/aBooDyy/Progress-Expansion/issues/2)
He fixed it by adding not only a placeholder like this: `{placheolder}`
But also like this: `$(placeholder)$`

The question is, can you implement the same thing in your expansion?

I've also tried another solution which doesn't seem to work as intended: shortcut placeholder. It doesn't seem to like anything with curly brackets. Anyway, i hope you can fix this. Thanks in advance.

**Comment by Kqliber** [comment]
Closing this issue as [Utils Expansion](https://api.extendedclip.com/expansions/utils/) exists to parse an infinite amount of nested placeholders

(sorry for the 18 month reply!)
